### ISSUE TITLE
Light gray lines in -html output

### ISSUE THREAD

**Issue by rogpeppe** [wadey/gocovmerge#1] opened 2015-10-29 11:31 UTC
I really wanted this to work, but when I run go tool cover -html, I see
not just dark gray, green and red lines, but also light gray lines of
code. It is not obvious whether those lines are covered or not.
![profilehtml](https://cloud.githubusercontent.com/assets/66491/10817177/1ff8f48a-7e30-11e5-873c-0d5082cd990f.png)

I generated the coverage output by doing:

```
   cd $GOPATH/github.com/juju/juju/api
   go test -coverprofile /tmp/c.out
   cd ../apiserver/client
   go test -coverkg github.com/juju/juju/api -coverprofile d.out
   gocovmerge /tmp/c.out /tmp/d.out > /tmp/e.out
   go tool cover -html /tmp/e.out
```

**Comment by wadey** [comment] 2015-10-29 13:47
Good find, It looks like the light grey lines are lines that are covered by one output file but not the other one. I have been using `gocov-xml` and viewing the test results inside of Jenkins which I think doesn't show this issue.

I can reproduce the issue locally so I will see if I can get the output corrected for the html viewer.

Thanks for reporting this in such an easy to reproduce fashion.

**Comment by wadey** [comment] 2015-10-29 13:58
I pushed a fix for this, it looks like the HTML formatter expects the coverage count to be either `1` or `0`, not the incrementing count that I was using.

**Closed as completed** 2015-10-29 13:57 UTC
