### ISSUE TITLE
when does OVERLAP MERGE happen?

### ISSUE THREAD

**Issue by yonderblue** [wadey/gocovmerge#4] opened 2016-06-15 17:37 UTC
I am trying to understand the case that I am getting this error from. Could you explain when that is?

Since its valid to take profiles from different runs "overlap" sounds like a normal case.

**Comment by wadey** [comment] 2016-06-15 17:46
The only time I have seen it happen is when you try to merge profiles that are from different versions of the source code. If your source code doesn't change between runs, you shouldn't have any overlap issues. Can you confirm that none of your source code has changed between the profile runs?

**Comment by wadey** [comment] 2016-06-15 17:52
I'll work on a patch that makes these error messages a little more understandable

**Comment by yonderblue** [comment] 2016-06-15 20:07
ok thanks, i'll check on the versions

**Comment by yonderblue** [comment] 2016-06-16 23:05
Seem to be the same version, but still getting the error. I can send you some files if you wish, but would rather not post them here.

**Comment by wadey** [comment] 2016-06-16 23:41
Sure, my email address is on my GitHub profile page. Send me the files and the commands you are running to get the traces and I will see if I can reproduce.

**Comment by yonderblue** [comment] 2016-07-11 17:42
[a.txt](https://github.com/wadey/gocovmerge/files/357682/a.txt)
[b.txt](https://github.com/wadey/gocovmerge/files/357683/b.txt)

Ok here are two coverage profiles that I santized (removed leading paths and removed other package lines except this one dealing with sqlite since the conflict happens here. Does this shed any light?

It was two different test runs from the same source code, however the test binaries might have been built differently. One likely had the race detector on and one not. Was probably also two different architectures. Would either of those make a difference?

**Comment by wadey** [comment] 2016-07-11 18:24
Are you sure this is using the same `sqlite.go` file? a.txt goes up to line 365 but b.txt goes to line 2228. Seems like maybe they were not using the same source file.

I will do some experimentation to see if having race detector or using different architectures could affect the output.

**Comment by yonderblue** [comment] 2016-07-11 20:18
I'm almost certain it is the same source, but even if it wasn't it would be fairly close in line numbers. Aren't those just the lines hit?

**Comment by wadey** [comment] 2016-07-11 20:33
Those are the chunks of code that the file was split into for coverage and it includes lines that were not hit. The last number on the line is the number of times that line was executed, with `0` being "unhit". That is why the chunks should match for the same source file.

The format for the file is described here: https://github.com/golang/tools/blob/c887be1b2ebd11663d4bf2fbca508c449172339e/cover/profile.go#L51-L54

**Comment by yonderblue** [comment] 2016-07-12 00:26
I see, perhaps it splits the chunks differently in different kinds of runs with the same source. However with a format like that it seems we could merge chunks regardless of how they overlap if the end is exclusive?

**Comment by wadey** [comment] 2016-07-12 00:32
we could, but I have only seen this error before when the source code didn't match, and since the line numbers seem to be off by thousands of lines in your example I'm still not convinced that the source files were the same. How many lines do you expect this file to have since the two line counts appears to be either around ~300 lines or ~2200 lines. Can you still reproduce this issue after rerunning the `go test -coverprofile` runs?

**Comment by wadey** [comment] 2016-07-12 00:34
Can you run `go tool cover -html=<coverprofile>` which each of your outputs and make sure it looks correct for the `sqlite/sqlite.go` file?

**Comment by wadey** [comment] 2017-01-11 19:53
Closing this since no further information was added. Please re-open if you have more details.

**Closed as completed by wadey** 2017-01-11 19:53 UTC

**Comment by aryanmehrotra** [comment] 2024-02-26 07:03
Hi @wadey what about having a flag which can merge overlapping reports, the one with more coverage is given preference.
I have been working on a framework https://github.com/gofr-dev/gofr and I have decided to separate out the tests such that to make the pipeline faster, and if I have this feature it would be useful.
